name: AWS connection test
on:
  push:
    branches: [gha-aws]
    paths: ['scripts/aws-test/**']

jobs:
  aws-test-job:
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Sysdig
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: arn:aws:iam::368293260341:role/RoleTestForGithubActions
          aws-region: us-east-1

      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Setup poetry
        uses: abatilo/actions-poetry@v2.0.0

      - name: Install deps
        working-directory: scripts/aws-test
        run: poetry install

      - name: Run script
        working-directory: scripts/aws-test
        run: poetry run ./do_test.py
