name: Build and test

on:
  workflow_call:
    inputs:
      builder_image:
        description: 'The builder image pull string'
        required: true
        type: string

jobs:
  build-linux:
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.builder_image }}
    steps:
      - name: Checkout Sysdig
        uses: actions/checkout@v2
        with:
          path: ${{ github.workspace }}/sysdig
      - name: Checkout libs
        uses: actions/checkout@v2
        with:
          repository: lucklypse/libs
          ref: fix/safer-strings-gcc-8
          path: ${{ github.workspace}}/libs
      - name: Link paths
        run: |
          mkdir -p /source
          ln -s "${{ github.workspace }}/sysdig" /source/sysdig
          ln -s "${{ github.workspace }}/libs" /source/libs
          ls -lah /source/sysdig
          ls -lah /source/libs
      - name: Build
        run: build cmake
      - name: Build packages
        run: build package