name: Build and test

on:
  workflow_call:
    inputs:
      builder_image:
        description: 'The builder image pull string'
        required: true
        type: string

jobs:
  build-linux:
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.builder_image }}
    steps:
      - name: Checkout Sysdig
        uses: actions/checkout@v2
        with:
          path: ${{ github.workspace }}/source
      - name: Checkout libs
        uses: actions/checkout@v2
        with:
          repository: lucklypse/libs
          ref: fix/safer-strings-gcc-8
          path: ${{ github.workspace}}/libs
      - name: Link paths
        run: |
          ln -s "${{ github.workspace }}/source" /source
          ln -s "${{ github.workspace }}/libs" /libs
      - name: Build
        run: build cmake
      - name: Build packages
        run: build package