name: Get the latest builder tag
on:
  push:
    paths:
      - '**'
      - '!docker/builder/**'

permissions:
  contents: read
  packages: write

jobs:
  get-latest-builder-tag:
    runs-on: ubuntu-latest
    outputs:
      builder_image: ${{ steps.read-builder-image.outputs.builder_image }}
    steps:
      - name: Checkout Sysdig
        uses: actions/checkout@v2
      - name: Read latest builder image
        id: read-builder-image
        run: |
          echo "::set-output name=builder_image::$(grep 'ARG BUILDER_IMAGE=' '${{ github.workspace }}/docker/sysdig/Dockerfile' | cut -d '=' -f 2 | cut -d ' ' -f 1)"
  build-ci:
    needs: get-latest-builder-tag
    uses: lucaguerra/sysdig/.github/workflows/ci-build-and-test.yaml@new/builder-workflow
    # uses: ${{ github.repository_owner }}/${{ github.repository }}/.github/workflows/ci-build-and-test.yaml@${{ github.sha }}
    with:
      builder_image: ${{ needs.get-latest-builder-tag.outputs.builder_image }}

#          BUILDER_IMAGE=$(grep 'ARG BUILDER_IMAGE=' "${{ github.workspace }}/docker/sysdig/Dockerfile" | cut -d '=' -f 2 | cut -d ' ' -f 1)
#          echo "BUILDER_IMAGE=${BUILDER_IMAGE}" >> $GITHUB_ENV
