name: Build builder container if changed
on:
  push:
    paths:
      - 'docker/builder/**'

env:
  REGISTRY: ghcr.io
  BUILDER_IMAGE_BASE: ${{ env.REGISTRY }}/lucaguerra/sysdig/builder

permissions:
  contents: read
  packages: write

jobs:
  build-builder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Sysdig
        uses: actions/checkout@v2
      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build builder
        uses: docker/build-push-action@v2
        with:
          context: docker/builder
          tags: ${{ env.BUILDER_IMAGE_BASE }}:${{ github.sha }}
    outputs:
      builder_image: ${{ env.BUILDER_IMAGE_BASE }}:${{ github.sha }}
