name: CI Build
on: [pull_request] # to be changed in pull_request: branches: - main (or the used main branch)

jobs:
  build-sysdig-linux:
    runs-on: ubuntu-latest
    container:
      image: docker/builder/Dockerfile
    steps:
      - name: Checkout Sysdig
        uses: actions/checkout@v2
        with:
          path: sysdig
      - name: Checkout libs
        uses: actions/checkout@v2
        with:
          repository: falcosecurity/libs
          ref: 396f2c936a6941462c0ea7ff29fe6157481df96d
          path: libs
      - name: Link paths
        run: |
          mkdir -p /source
          ln -s "$GITHUB_WORKSPACE/sysdig" /source/sysdig
          ln -s "$GITHUB_WORKSPACE/libs" /source/libs
      - name: Build
        run: build cmake
      - name: Build packages
        run: build package
