name: CI Build
on: [push]

jobs:
  builder:
    env:
      REGISTRY: ghcr.io
      BUILDER_IMAGE_BASE: ghcr.io/lucaguerra/sysdig-builder

    runs-on: ubuntu-latest
    steps:
      - name: Checkout Sysdig
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Check if builder is modified
        id: builder-files
        uses: tj-actions/changed-files@v10.1
        with:
          files: |
            ^docker/builder

      - name: Get latest builder tag
        id: get-builder
        run: |
          echo "::set-output name=builder_image::$(grep 'ARG BUILDER_IMAGE=' '${{ github.workspace }}/docker/sysdig/Dockerfile' | cut -d '=' -f 2 | cut -d ' ' -f 1)"

      - name: Login to Github Packages
        if: steps.builder-files.outputs.any_changed == 'true'
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Get new builder image tag
        id: get-new-builder
        if: steps.builder-files.outputs.any_changed == 'true'
        run: |
          echo "::set-output name=builder_image::${{ env.BUILDER_IMAGE_BASE }}:${{ github.sha }}"

      - name: Build new builder
        id: build-builder
        if: steps.builder-files.outputs.any_changed == 'true'
        uses: docker/build-push-action@v2
        with:
          context: docker/builder
          tags: ${{ steps.get-new-builder.outputs.builder_image }}
          push: true

    outputs:
      builder_image: ${{ (steps.builder-files.outputs.any_changed == 'true') && steps.get-new-builder.outputs.builder_image || steps.get-builder.outputs.builder_image }}

  build-sysdig-linux:
    needs: builder
    runs-on: ubuntu-latest
    container:
      image: ${{ needs.builder.outputs.builder_image }}
    steps:
      - name: Checkout Sysdig
        uses: actions/checkout@v2
        with:
          path: sysdig
      - name: Checkout libs
        uses: actions/checkout@v2
        with:
          repository: lucklypse/libs
          ref: fix/safer-strings-gcc-8
          path: libs
      - name: Link paths
        run: |
          pwd
          env | grep -i github_workspace
          ls -lah
          mkdir -p /source
          ln -s $(pwd)/sysdig /source/sysdig
          ln -s $(pwd)/libs /source/libs
          ls -lah /source/sysdig/*
      - name: Build
        run: build cmake
      # - name: Build packages
      #   run: build package
