name: Create Sysdig stub draft release
on:
  push:
    tags:
      - 'test-[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-fake-release-linux:
    runs-on: ubuntu-latest
    env:
      BUILD_VERSION: ${{ github.ref_name }}
    container:
      image: ghcr.io/lucaguerra/sysdig-builder:dev
    steps:
      - name: Stub build packages
        run: |
          mkdir -p /build/release
          echo "targzm placeholder" > /build/release/sysdig-${{ github.ref_name }}-x86_64.tar.gz
          echo "deb placeholder" > /build/release/sysdig-${{ github.ref_name }}-x86_64.deb
          echo "rpm placeholder" > /build/release/sysdig-${{ github.ref_name }}-x86_64.rpm
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: sysdig-${{ env.BUILD_VERSION }}
          path: /build/release/sysdig-${{ env.BUILD_VERSION }}*

  create-draft-release:
    runs-on: ubuntu-latest
    env:
      BUILD_VERSION: ${{ github.ref_name }}
    # needs: [push-container-image, build-release-linux]
    needs: [build-fake-release-linux]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: sysdig-${{ env.BUILD_VERSION }}
      - name: Create draft release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            sysdig-${{ github.ref_name }}-x86_64.tar.gz
            sysdig-${{ github.ref_name }}-x86_64.deb
            sysdig-${{ github.ref_name }}-x86_64.rpm
          draft: true
        # sysdig-stub-test-0.27.109.deb
        # sysdig-stub-test-0.27.109.rpm
        # sysdig-stub-test-0.27.109.tar.gz

