name: Finalize release
on:
  release:
    types: [published]

jobs:
  upload-files:
    runs-on: ubuntu-latest
    env:
      RELEASE: ${{ github.event.release.name }}
    steps:
      - name: Download targz
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          version: "tags/${{ env.RELEASE }}"
          file: sysdig-${{ env.RELEASE }}-x86_64.tar.gz
          target: sysdig-${{ env.RELEASE }}-x86_64.tar.gz
          token: ${{ secrets.GITHUB_TOKEN }}
