name: Create Sysdig draft release
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-release-linux:
    runs-on: ubuntu-latest
    env:
      BUILD_VERSION: ${{ github.ref_name }}
    container:
      image: ghcr.io/lucaguerra/sysdig-builder:dev
    steps:
      - name: Checkout Sysdig
        uses: actions/checkout@v2
        with:
          path: sysdig
      - name: Link paths
        run: |
          mkdir -p /source
          ln -s "$GITHUB_WORKSPACE/sysdig" /source/sysdig
      - name: Build
        run: build cmake
      - name: Build packages
        run: build package
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: sysdig-release-${{ env.BUILD_VERSION }}
          path: /build/release/sysdig-${{ env.BUILD_VERSION }}*

  push-container-image:
    runs-on: ubuntu-latest
    env:
      BUILD_VERSION: ${{ github.ref_name }}
      REGISTRY: ghcr.io
      SYSDIG_IMAGE_BASE: ghcr.io/lucaguerra/sysdig # CHANGE this for draios
    steps:
      - name: Checkout Sysdig
        uses: actions/checkout@v2
      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push container images
        uses: docker/build-push-action@v2
        with:
          file: docker/sysdig/Dockerfile
          context: .
          tags: ${{ env.SYSDIG_IMAGE_BASE }}:${{ env.BUILD_VERSION }}
          push: true
          build-args:
            BUILD_VERSION=${{ env.BUILD_VERSION }}

  create-draft-release:
    runs-on: ubuntu-latest
    needs: [push-container-image, build-release-linux]
    env:
      BUILD_VERSION: ${{ github.ref_name }}
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: sysdig-release-${{ env.BUILD_VERSION }}
      - name: Create draft release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            sysdig-${{ github.ref_name }}-x86_64.tar.gz
            sysdig-${{ github.ref_name }}-x86_64.deb
            sysdig-${{ github.ref_name }}-x86_64.rpm
          draft: true
